### ISSUE TITLE
Geolocation has changed to wrong location

### ISSUE THREAD

**Issue by benjaminh83** [filecoin-saturn/L1-node#102]
Been running my node since Sunrise and it has always reported to San Diego, but now it has switched to Irvine, which is not really close. 

6fadfadc 🌅️ | L1v465 | 38.xxx.xxx.236Cogent Communications | IrvineUnited States (US)
-- | -- | -- | --

**Comment by DiegoRBaquero** [comment]
Fixed

**Comment by leenorvall** [comment]
As of v470 we are now getting this issues with node reporting location as Cambridge UK but was previously correct with London.

**Comment by DiegoRBaquero** [comment]
Version does not affect geolocation. Please report your IP address and exact location to IPInfo support: https://ipinfo.io/contact
