### ISSUE TITLE
Map docker images to their git tags

### ISSUE THREAD

**Issue by joaosa** [filecoin-saturn/L1-node#111]
Versioning is displayed per node on the stats page ([production](https://orchestrator.strn.pl/stats) and [staging](https://orchestrator.strn-test.pl/stats)). 

This number (e.g. `v475`) corresponds to a CI build number and not to the actual version associated to the git commit which triggered it (e.g. `1668199595`). 
If multiple builds were to occur for a particular commit and those were to produce different docker image artifacts, we wouldn't be able to relate them. One way to fix this is to keep both values in mind and to display them together (e.g. `v1668199595-b475`).

Another aspect to consider is the versioning of docker images. We're currently using mutable docker tags for client convenience. It's easy to ensure we have the latest version with a `docker pull ghcr.io/filecoin-saturn/l1-node:main`. We get environment scoping for free, i.e. the latest staging image does not get mixed with the latest production one.

This is, however, not ideal if we were to need to troubleshoot what is going on with a particular version. As docker tags are mutable, they move to the latest image pushed to that tag. This leaves behind a set of images we have little information about ([see here](https://github.com/filecoin-saturn/L1-node/pkgs/container/l1-node/versions)). The need to debug past images may not be aligned with keeping the network running the latest version, but it could be invaluable for ensuring there is no performance degradation between versions (for instance).

One approach would be to use a single immutable docker image tag (note that `ghrc.io` does not seem to enforce this principle [the way AWS does](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-tag-mutability.html)) as opposed to rolling tags (i.e. tags which point to the last image pushed with that tag). Following this would ensure a particular image tag cannot be overwritten and will always map to the version it originated from.

This also means giving up the client-side UX of fetching the latest image with a simple docker command. This could be fine if properly documented given version numbers are typically monotonic increasing in their sequence (i.e. version `1668199595` is ensured to come after `1667316793`).
Also noteworthy is the fact this approach doesn't work with [watchtower](https://github.com/containrrr/watchtower/issues/460) for [auto-updates](##Auto-update).

To work around this, we could tag images twice. Both with their git commit tag and target environment. This way we would be able to map one to a particular git commit while preserving the client UX side of things.

**Comment by vorburger** [comment]
> To work around this, we could tag images twice. Both with their git commit tag and target environment. 

+1 - I think this would be a great! FYI I've also seen other container images do exactly this in the past, it's common.

PS I'm personally using neither your `update.sh`, nor WatchTower, but another similar tool (for a different container environment, K8s) called _Keel,_ and they also have a [Policy](https://keel.sh/docs/#policies) to support this "image tagging version model"  - that project calls this "a `force` with `match-tag`"... perhaps seeing this support in 2 tools helps to "validate" this approach.
