### ISSUE TITLE
Container should run with docker run --read-only and not write to its root file system (anywhere else than the mounted volume)

### ISSUE THREAD

**Issue by vorburger** [filecoin-saturn/L1-node#114]
Looking at [`run.sh`](https://github.com/filecoin-saturn/L1-node/blob/main/run.sh) made me think that the `ghcr.io/filecoin-saturn/l1-node:main` container only needs to be able to write `/usr/src/app/shared`, but this does not appear to be so; if I run this image with everything but this read-only (e.g. using `readOnlyRootFilesystem: true` in Kubernetes; but this isn't K8s specific per se, you could see the same with simple Docker) there are a number of errors:

```
sed: couldn't open temporary file /etc/nginx/confs/sedRfbydb: Read-only file system
Sat Nov 19 23:02:42 UTC 2022 [container] booting
Sat Nov 19 23:02:42 UTC 2022 [container] CPUs: 12
Sat Nov 19 23:02:42 UTC 2022 [container] Memory: MemTotal:65411432kB MemFree:62972952kB MemAvailable:63891360kB
Sat Nov 19 23:02:42 UTC 2022 [container] Disk: /dev/nvme1n1p1  954G  6.7G  947G   1% /usr/src/app/shared
mkdir: cannot create directory '/usr/src/app/shared/ssl': Permission denied
Sat Nov 19 23:02:42 UTC 2022 [container] SSL config unavailable, starting non-TLS nginx and node shim
cp: cannot create regular file '/etc/nginx/conf.d/L1.conf': Read-only file system
2022/11/19 23:02:42 [warn] 29#29: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:4
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:4
2022/11/19 23:02:42 [warn] 29#29: duplicate MIME type "text/html" in /etc/nginx/nginx.conf:66
nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/nginx.conf:66
2022/11/19 23:02:42 [emerg] 29#29: open() "/etc/nginx/conf.d/L1.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/proxy.conf:11
nginx: [emerg] open() "/etc/nginx/conf.d/L1.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/proxy.conf:11
[Error: EACCES: permission denied, open './shared/nodeId.txt'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: './shared/nodeId.txt'
}
2022-11-19T23:02:43.268Z node-main Saturn L1 Node
2022-11-19T23:02:43.268Z node-main:id [REDACTED]
2022-11-19T23:02:43.269Z node-main:version 479_407b913
2022-11-19T23:02:43.269Z node-main:important ===== IMPORTANT =====
2022-11-19T23:02:43.269Z node-main:important Earnings will be sent to Filecoin wallet address: [REDACTED]
2022-11-19T23:02:43.269Z node-main:important Payment notifications and important update will be sent to: [REDACTED]
2022-11-19T23:02:43.269Z node-main:important ===== IMPORTANT =====
2022-11-19T23:02:43.275Z node-main:server shim process running
```

Perhaps it would be useful for operators to clarify in documentation what the following files and folders are used for, and if they need to / should be "persisted" (like `/usr/src/app/shared`) or can be considered "ephemeral" and it's OK if they are lost on each container restart:

```
/etc/nginx/confs/sedRfbydb
/usr/src/app/shared/ssl
/etc/nginx/conf.d/L1.conf
./shared/nodeId.txt
```

**Comment by vorburger** [comment]
Clarification: Technically I didn't just run it with a read-only container root file system, but also ran the container as a non-root user (for better security posture), and it's the combination of both of these which causes the error above. Would any pull requests to improve upon this be welcome contributions to this project?

**Comment by vorburger** [comment]
#99 make me think that once it will successfully run it will also write logs to `/var/log/` inside the container, such as `/var/log/nginx/node-access.log`? That's perhaps not idea either; it may be better to just stream to STDOUT, as per e.g. https://12factor.net/logs.

**Comment by vorburger** [comment]
```
root@saturn-0:/usr/src/app/shared# ls -al /etc/nginx/confs
total 8
drwxr-xr-x 1 root root   28 Nov 26 03:40 .
drwxr-xr-x 1 root root  130 Nov 26 03:40 ..
-rw-r--r-- 1 root root  459 Nov 23 19:54 non_tls_proxy.conf
-rw-r--r-- 1 root root 2242 Nov 26 03:40 tls_proxy.conf
root@saturn-0:/usr/src/app/shared# ls -al /etc/nginx/conf.d/
total 16
drwxr-xr-x 1 root root   21 Nov 26 03:40 .
drwxr-xr-x 1 root root  130 Nov 26 03:40 ..
-rw-r--r-- 1 root root 2242 Nov 26 03:40 L1.conf
-rw-r--r-- 1 root root 1568 Nov 23 19:54 proxy.conf
-rw-r--r-- 1 root root  375 Nov 23 19:54 register.conf
-rw-r--r-- 1 root root 3819 Nov 23 19:54 shared.conf
```

> also write logs to /var/log/

```
root@saturn-0:/usr/src/app/shared# ls -al /var/log/nginx/
total 4
drwxr-xr-x 1 root root   29 Nov 26 03:40 .
drwxr-xr-x 1 root root   19 Nov 21 20:44 ..
lrwxrwxrwx 1 root root   11 Nov 15 13:14 access.log -> /dev/stdout
lrwxrwxrwx 1 root root   11 Nov 15 13:14 error.log -> /dev/stderr
-rw-r--r-- 1 root root 1394 Nov 26 03:59 node-access.log

root@saturn-0:/usr/src/app/shared# cat /var/log/nginx/node-access.log
url=https://strn.pl/ipfs/QmQ12nfk6msFP8VkwVjgiCaQL1ZwWXpW8PFApEs3JDwdiY/Photos/JavHub - Kokomi Hoshino On Thursday October 22 2020.jpg&&args=format=car&clientId=f19f5bae-9ad2-4de3-bc7c-9a560999aac4&&ua=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36&&rid=52c00a6fb16ebd38a4003bc1f34d59fd&&s=200&&b=232913&&range=-&&lt=2022-11-26T03:58:25+00:00&&rt=0.143&&addr=10.244.0.1&&ff=-&&ref=https://anime-sama.fr/&&uct=-&&uht=-&&urt=-&&ucs=HIT&&sp=HTTP/2.0
(...)
```

**Comment by vorburger** [comment]
> Perhaps it would be useful for operators to clarify in documentation what the following files and folders are used for, and if they need to / should be "persisted" (like /usr/src/app/shared) or can be considered "ephemeral" and it's OK if they are lost on each container restart:

Let's do that documentation in #127.

Let's keep this issue focused on supporting `docker run --readonly`.

**Comment by guanzo** [comment]
> #99 make me think that once it will successfully run it will also write logs to `/var/log/` inside the container, such as `/var/log/nginx/node-access.log`? That's perhaps not idea either; it may be better to just stream to STDOUT, as per e.g. https://12factor.net/logs.

These access logs are submitted to our backend for metrics & earnings calculations, so it kind of needs to happen inside the container.

**Comment by vorburger** [comment]
> These access logs are submitted to our backend for metrics & earnings calculations, so it kind of needs to happen inside the container.

Wehl... yes and no. Perhaps perhaps there could be an explicit "ephemeral" volume for those?

https://github.com/docker-library/docs/tree/master/nginx#running-nginx-in-read-only-mode FYI.

**Comment by DiegoRBaquero** [comment]
nginx and other processes in the system might write logs, the shim only writes in the volume, but we don't want to break other processes, we don't own the whole stack
