### ISSUE TITLE
“registration Node's geolocation” wrong for L1 node

### ISSUE THREAD

**Issue by coinmini** [filecoin-saturn/L1-node#128]
Hi, Team

nodeId: 3a419435-9d15-4841-8db0-a95a70e0ad05
IP: 23.237.166.50
It should be:  Minnetonka , Minnesota , United States
"saturn-saturn-node-1  | 2022-11-27T15:07:52.776Z node-main:registration Node's geolocation is set to Avon Park, Florida, United States. If this is wrong, please open an issue at https://github.com/filecoin-saturn/L1-node/issues

thanks

**Comment by coinmini** [comment]
Hi, Team
nodeID: 4fd9a6c0-f793-432c-b9ea-280698b6fce8
IP: 23.237.116.98
It should be:  Denver ，Colorado， US

saturn-saturn-node-1  | 2022-11-28T01:32:03.678Z node-main:registration Node's geolocation is set to Avon Park, Florida, United States. If this is wrong, please open an issue at https://github.com/filecoin-saturn/L1-node/issues

**Comment by DiegoRBaquero** [comment]
Do you have exact coordinates for them?

**Comment by coinmini** [comment]
Hi, Diego
heres the info

**nodeID: 4fd9a6c0-f793-432c-b9ea-280698b6fce8
IP: 23.237.116.98**

Check info: 
https://whatismyipaddress.com/ip/23.237.116.98
Decimal: 401437794
Hostname: 23.237.116.98
ASN: 174
ISP: FDCservers.net LLC
Services: Datacenter
Assignment: [Likely Static IP](https://whatismyipaddress.com/dynamic-static)
Country: United States
State/Region: Colorado
City: Denver

coordinates:
Latitude: 39.739151  (39° 44′ 20.94″ N)
Longitude: -104.984703  (104° 59′ 4.93″ W)

================================================

**nodeId: 3a419435-9d15-4841-8db0-a95a70e0ad05
IP: 23.237.166.50**
Check info: 

https://whatismyipaddress.com/ip/23.237.166.50
Decimal: 401450546
Hostname: 23.237.166.50
ASN: 174
ISP: FDCservers.net LLC
Services: Datacenter
Assignment: [Likely Static IP](https://whatismyipaddress.com/dynamic-static)
Country: United States
State/Region: Minnesota
City: Minnetonka

coordinates:
Latitude: 44.9133  (44° 54′ 47.88″ N)
Longitude: -93.503288  (93° 30′ 11.84″ W)

**Comment by coinmini** [comment]
post the FDCservers client info here 
![danver](https://user-images.githubusercontent.com/7355192/204394400-d5cfd76e-a414-4bd3-9730-72567d1284f1.jpeg)
![MNfdc](https://user-images.githubusercontent.com/7355192/204394426-587fd995-139d-4df1-92cc-4a7e0de18d2f.png)

**Comment by holdenk** [comment]
I think this is the same issue (more or less) as in https://github.com/filecoin-saturn/L1-node/issues/130

**Comment by DiegoRBaquero** [comment]
Fixed :D

**Comment by coinmini** [comment]
Cool, I can see the new location now. 
Good job, thank you 👍
