### ISSUE TITLE
Question: Does it care if all source IPs are the same?

### ISSUE THREAD

**Issue by vorburger** [filecoin-saturn/L1-node#143]
This issue is a technical question for clarification, and perhaps a possible minor documentation clarification, than a bug report or enhancement feature / request (perhaps label it as such):

How EXACTLY 😹  do you mean [the requirement](https://github.com/filecoin-saturn/L1-node#node-hardware-requirements) re. _"server with a static public IPv4 address"?_ Specifically, is putting a Saturn L1 Node on a private IP cool, as long as it gets the HTTP packets? E.g. is it cool to put something like a hardware load balancer or something in software like a Kubernetes Service IP or an Ingress  in front of it, or even just simple direct port forwarding from a home router? Or MUST it be "directly" exposed? (E.g. on the "[DMZ](https://en.wikipedia.org/wiki/DMZ_(computing))" in a home lab kind of set-up.)

Given that in #114 we learnt that `/var/log/nginx/node-access.log` is (quote) _"submitted to our backend for metrics & earnings calculations"_ I'm wondering if it matters to anything in the currently secret sauce on the backend in the Orchestrator if the source IP which appears in the `addr=` field of those logs is always the same.

Perhaps it would worth to clarify this.

**Comment by DiegoRBaquero** [comment]
You can put it behind a private IP, but there still must be a public static IPv4 anyways, the one in front.

if it breaks nginx that's an issue, let me know if this is happening
