### ISSUE TITLE
Dying traffic on the node

### ISSUE THREAD

**Issue by michaltarana** [filecoin-saturn/L1-node#146]
Hi, I installed the l1 node and it successfully started to operate. The wallet was validated, I can see the cache growing, cache misses, cache building, everything looks quite normal in the logs. However, as the node re-registers every few minutes, I see decreasing traffic between each consecutive re-registers.

I still see some network connections opening at port 443, many packets seem to be empty, though. The logs do not contain any other information but re-registering. The weight of the node falls from inital ~70 to ~30 and stays like that for days.

The hw criteria are met, it is running on an fdc server. No firewall, no other interfering service or process. The packet counters are not growing, neither is the occupied disk space.

I tried to restart the node gracefully, tried to reinstall the container, everytime with the same result: Great initial performance that dies within several hours.

Is there anything I could try to diagnose the problem? Thank you for any comments and have a nice day.

**Comment by gruns** [comment]
cc @DiegoRBaquero

**Comment by gruns** [comment]
hey michal!

if you haven't already, try asking your question in the #filecoin-saturn channel on filecoin slack! 🙌 join here: https://filecoinproject.slack.com/archives/C03DH0BL02E

**Comment by uberneo** [comment]
@michaltarana @DiegoRBaquero  I am seeing the exact same behaviour on my node as well. Any solution to debug this issue during this past 1 month ? thanks
