### ISSUE TITLE
please help me，and no discord？？

### ISSUE THREAD

**Issue by zxc348369518** [filecoin-saturn/L1-node#148]
Why do nodes keep breaking down automatically? Some nodes meet all the requirements, but they just can't run the program. Failed initial registration: SyntaxError Unexpected token < in JSON at position 0 +3m? Always automatically update server requirements, why?

**Comment by zxc348369518** [comment]
node@mainnet:local-nodes Refreshing local nodes +5m
  node@mainnet:local-nodes Local nodes refreshed, undefined nodes found +51ms
After an hour of normal operation, he keeps showing this, wireless recirculation, no revenue, why?? How to solve it?

**Comment by zxc348369518** [comment]
node@mainnet:local-nodes Local nodes refreshed, 5 nodes found +538ms
2022/12/16 00:06:08 [error] 46#46: *67 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 65.189.42.178, server: _, request: "GET /ipfs/QmZAsnuhnwwJAP6QBEJgevVnAiVi5ALGa2Ng3DcpWgrQ42?format=car&clientId=7afe30ed-2ce7-47f4-89af-52768e9d564a HTTP/2.0", upstream: "http://127.0.0.1:10361/ipfs/QmZAsnuhnwwJAP6QBEJgevVnAiVi5ALGa2Ng3DcpWgrQ42?format=car&clientId=7afe30ed-2ce7-47f4-89af-52768e9d564a", host: "strn.pl", referrer: "https://flow.tellygossips.net/"
  node@mainnet:error Client aborted early, terminating gateway request +0  
this is why？？

**Comment by zxc348369518** [comment]
node@mainnet:system Memory Total: 64.8 GB Free: 63 GB Available: 63.3 GB +0ms
  node@mainnet:system Disk Total: 10407 GB Used: 4 GB Available: 10403 GB +5ms
  node@mainnet:system CPUs: 8 (0.53, 0.2, 0.07) +21ms
  node@mainnet:system NIC ens5: 833 MB downloaded / 2.28 GB uploaded +4ms
  node@mainnet:registration All requirements met +0ms
  node@mainnet:system Executing speedtest +0ms
  node@mainnet:system Done executing speedtest. 2647.1623360000003 Mbps DL / 4783.741480000001 Mbps  UL +19s
  node@mainnet:registration Speed requirement met +19s
  node@mainnet:registration Certificate is valid until Mar 15 23:59:59 2023 GMT +1ms
  node@mainnet:registration Re-registering with orchestrator... +0ms
  node@mainnet:registration:check Successful +0ms
  node@mainnet:registration Node's geolocation is set to Hilliard, Ohio, United States. If this is wrong, please open an issue at https://github.com/filecoin-saturn/L1-node/issues +2s
  node@mainnet:registration Successful re-registration, updated token +0ms
  node@mainnet:log-ingestor Reading nginx log file +0ms
  node@mainnet:local-nodes Refreshing local nodes +0ms
  node@mainnet:local-nodes Local nodes refreshed, 5 nodes found +603ms
2022/12/16 01:11:06 [notice] 49#49: http file cache: /usr/src/app/shared/nginx_cache 84.785M, bsize: 4096
2022/12/16 01:11:06 [notice] 29#29: signal 17 (SIGCHLD) received from 49
2022/12/16 01:11:06 [notice] 29#29: cache loader process 49 exited with code 0
2022/12/16 01:11:06 [notice] 29#29: signal 29 (SIGIO) received
  node@mainnet:system Memory Total: 64.8 GB Free: 63 GB Available: 63.3 GB +2m
  node@mainnet:system Disk Total: 10407 GB Used: 4 GB Available: 10403 GB +4ms
  node@mainnet:system CPUs: 8 (0.04, 0.12, 0.06) +20ms
  node@mainnet:system NIC ens5: 4.24 GB downloaded / 4.58 GB uploaded +3ms
  node@mainnet:registration All requirements met +2m
  node@mainnet:registration Re-registering with orchestrator... +0ms
  node@mainnet:registration:check Successful +0ms
  node@mainnet:registration Node's geolocation is set to Hilliard, Ohio, United States. If this is wrong, please open an issue at https://github.com/filecoin-saturn/L1-node/issues +1s
  node@mainnet:registration Successful re-registration, updated token +0ms
  node@mainnet:local-nodes Refreshing local nodes +5m
  node@mainnet:local-nodes Local nodes refreshed, 5 nodes found +748ms
Please help me solve this problem, thank you。

**Comment by zxc348369518** [comment]
Failed initial registration: SyntaxError Unexpected token < in JSON at position 0 +3m

**Comment by DiegoRBaquero** [comment]
If you encounter this error please reach us through slack, it should not happen and we can start investigating.

Sadly no discord.
