### ISSUE TITLE
Does saturn L1 require inbound traffic to be open for 80 and 443? 

### ISSUE THREAD

**Issue by jenks-guo-filecoin** [filecoin-saturn/L1-node#149]
Hi Team, a quick one but unable to find the answer in docs. 

Does Saturn L1 require an internet connection to have inbound traffic open for 80 & 443? If not, could we get around it somehow? 

![image](https://user-images.githubusercontent.com/100632895/208548561-b0fdb426-6d2a-4f12-bb04-19809f1d0211.png)

**Comment by AnomalRoil** [comment]
Yes it does. But on my side I've succeeded putting it behind a reverse proxy

**Comment by DiegoRBaquero** [comment]
Both are needed, as those are the HTTP and HTTPS traffic ports, that's how Saturn receives the traffic. There's no way around it
