### ISSUE TITLE
Useless weight

### ISSUE THREAD

**Issue by qianhh** [filecoin-saturn/L1-node#158]
I have serious doubts about this weight. The highest weight has no traffic, but the weight node with penalty is allocated so much traffic. Can you explain the reason?
![1672017773085](https://user-images.githubusercontent.com/17694389/209488169-c49e6524-149a-4cde-b950-405ef3d106bc.jpg)

**Comment by kwypchlo** [comment]
The "Upload" and "Download" stats can be inaccurate as they contain all traffic in and out of the server, not only the Saturn node traffic. We are working on improving those.
