### ISSUE TITLE
Payment schedule question

### ISSUE THREAD

**Issue by guglez** [filecoin-saturn/L1-node#160]
Hi,

what's the payment schedule? December ended but I see no payments. How to get an invite to the slack channel?

**Comment by Sneg90** [comment]
December payments came in yesterday.
  I also have a question, how to get an invite to slack?

**Comment by guglez** [comment]
I did not receive any payments. Is something wrong?

**Comment by DiegoRBaquero** [comment]
https://github.com/filecoin-saturn/L1-node/blob/main/docs/faq.md#when-do-i-receive-my-fil-payouts
