### ISSUE TITLE
Seems  GEO DB is not correct,  hope check the DB and use the very right one.

### ISSUE THREAD

**Issue by coinmini** [filecoin-saturn/L1-node#165]
We tried to deploy node at Ashburn , US these days. 

tried all the IP as follows:
38.107.226.x
142.202.49.x
172.111.38.x
They are all at  Ashburn,US. 

However,  at Saturn
38.107.226.x marked as  Miami, FL
142.202.49.x marked as  Chicago, Illinois
172.111.38.x marked as Chicago, Illinois

As you know, if IP marked as wrong place ,the TTFB would be high and weight would be low then no traffic .

**Comment by coinmini** [comment]
maybe you can consider using 
https://www.maxmind.com/en/geoip-demo

**Comment by DiegoRBaquero** [comment]
Please create issues per active node IPs that are wrong and I'll happily correct
