### ISSUE TITLE
Rewards calculation

### ISSUE THREAD

**Issue by stefanogalizia** [filecoin-saturn/L1-node#166]
Hi guys i have a question on earnings calculation, i have tried to ask the same on slack-channel but i think someone from protocol labs can have a better answer on this....
From the website providing a machine with 10gbps and 10TB of space should earn an estimated 282 FIL per month. Now i have this node id: 0427674f-ba32-42e8-b5d1-badcece835ce which has a good performance if you look on the dashboard, the currently estimated earnings are about 2FIL and the machine is up and running since 3 days, this is way far from the estimated earnings calculated on the website, at first i have thought that was because of the high cache hit rate penalty but now is around 3%. Am i misunderstood something? can someone explain? Thanks for all your work

**Comment by DiegoRBaquero** [comment]
The estimated earnings are for a region which does not have too many nodes and assuming great performance throughout the month.

There are currently a few region with too many nodes. And a few region where there are no nodes.

Happy to go over this through slack :)
