### ISSUE TITLE
Failed to check node, please make sure to have ports 80 and 443 open

### ISSUE THREAD

**Issue by lhllhx** [filecoin-saturn/L1-node#170]
node@testnet:registration Failed to check node, please make sure to have ports 80 and 443 open and accessible at 35.*.*.168 +439ms
  node@testnet:registration Failed re-registration Failed to check node, please make sure to have ports 80 and 443 open and accessible at 335.*.*.168 +1ms

I am sure my port is open and when I open ip, I can reach the website 
Only when I stop and delete the docker container and run run.sh again, the issuse will be fixed.

**Comment by DiegoRBaquero** [comment]
Are you running the container multiple times? It's very weird that stopping and running would solve the issue

**Comment by lhllhx** [comment]
It seem due to the update script. When the update script run, the script will make the version from main to test. When I delete the 
update script, all thing work fine. I have set SATURN_NETWORK=main environment variable. but it did not work in update script.

**Comment by lhllhx** [comment]
1 yes
2 yes

**Comment by DiegoRBaquero** [comment]
The update.sh script auto updates itself as well, so it shouldn't be modified.

You can set it in the cronjob command to make sure it's set
