### ISSUE TITLE
Cannot join Filecoin Slack channel

### ISSUE THREAD

**Issue by uberneo** [filecoin-saturn/L1-node#171]
Trying to register to Filecoin Slack channel but seems like its very difficult . 
I don't have account on any of the below mentioned sites and seems like they are not open for registration at all.
Appreciate if there is an any easy way to join this slack channel?

<img width="484" alt="image" src="https://user-images.githubusercontent.com/59272502/212521738-fd0897ac-4389-446b-b610-42bd983f6f4e.png">

**Comment by guchengdaoke** [comment]
I can't join either

I don't know why there is no discord(it's not difficult)

**Comment by DiegoRBaquero** [comment]
Try this link: https://filecoin.io/slack/

**Comment by DiegoRBaquero** [comment]
Closing as this is not an issue with Saturn itself
