### ISSUE TITLE
Multiple nodes detected on same hardware

### ISSUE THREAD

**Issue by uberneo** [filecoin-saturn/L1-node#172]
During the last update , something got missed and it created a new NodeId for my server. Luckily I had the backup of cache before the upgrade. However when i have now restored with the same old "shared" folder , it registered back with my old NodeId but after first successful registration its starts throwing below error 

```
node@mainnet:registration Multiple nodes detected on same hardware, please only run one node per physical uplink
node@mainnet:registration Failed re-registration Multiple nodes detected on same hardware, please only run one node per physical uplink
```
Right now only one NodeId is running on this server and I just want my old Node Id to be running as it is before and want to get rid of new NodeId .. Can this be done ?

**Comment by DiegoRBaquero** [comment]
If this happens, stop the node for at least 15 minutes. Then restart it.

Please check that `$SATURN_HOME` variable is correctly set in both `.bashrc` or equivalent and `/etc/environment` so it's loaded by cron update as well.

Node ID being changed shouldn't happen if everything is setup correctly.

Please ping me in slack if you have any further issues
