### ISSUE TITLE
Always send most current node ID

### ISSUE THREAD

**Issue by DiegoRBaquero** [filecoin-saturn/L1-node#180]
Instead of sending the node id from cache. Always inject it using latest node id.

This allows to copy cache folder, or sync them between multiple nodes.

**Comment by mrworkdev** [comment]
Good offer but it will affect TTFB. Not much but anyway.

**Comment by DiegoRBaquero** [comment]
This is already the case, we add headers on-the-fly https://github.com/filecoin-saturn/L1-node/blob/main/container/nginx/conf.d/shared.conf#L60
