### ISSUE TITLE
Error on node setup

### ISSUE THREAD

**Issue by DVerdeV** [filecoin-saturn/L1-node#197]
Hi! I'm setting up a new node, and I'm having an issue with the registration. Please, find a screenshot below:

![image](https://user-images.githubusercontent.com/99612385/215521816-269166f3-04cf-4944-993d-084a7e7ada1e.png)

Thanks!

**Comment by kwypchlo** [comment]
The registration node is currently experiencing some downtime, please check back in couple of hours.

**Comment by DVerdeV** [comment]
Solved a few hours later.
