### ISSUE TITLE
Hello, I have received my reward, but I found from the website that I have mined 100 coins, but I have actually received only 80 coins. When will the remaining 20 coins be issued?

### ISSUE THREAD

**Issue by zxc348369518** [filecoin-saturn/L1-node#210]
thanks，Hello, I have received my reward, but I found from the website that I have mined 100 coins, but I have actually received only 80 coins. When will the remaining 20 coins be issued?

**Comment by AmeanAsad** [comment]
What is your wallet address?

**Comment by zxc348369518** [comment]
> What is your wallet address?
see,f1ecjxiukzss3ccvlkstj4clhvwyiahm5ro72ub3y,show 155 but only get 129

**Comment by zxc348369518** [comment]
> What is your wallet address?
f1ueas2z7ood4ld63xk7mgdmpnucadh23ecttwe4y，look。website show i have

**Comment by AmeanAsad** [comment]
Hello @zxc348369518 😄 . You payouts show that you earned 92.32 FIL in January and you currently have that in the wallet you provided. You can check it [here](https://filfox.info/en/address/f1ueas2z7ood4ld63xk7mgdmpnucadh23ecttwe4y) on Filfox explorer. 

Keep in mind that payouts are monthly. So the last payout you only get paid for you contribution up to January 31st. Your account has a total earning of ~100 FIL but that factors in the first few days of February which were not included in the last payout period.
