### ISSUE TITLE
Geolocation fix

### ISSUE THREAD

**Issue by zxc348369518** [filecoin-saturn/L1-node#216]
15.220.240. xxx Could you please change the IP segment of xxx into Thailand? This is the newly opened country IP segment of Amazon, which has not been collected yet. Thank you.

**Comment by zxc348369518** [comment]
Where am I supposed to correct an IP that hasn't been broadcast yet?

**Comment by zxc348369518** [comment]
![image](https://user-images.githubusercontent.com/85321635/218227468-d12d5144-ffa4-4c4a-a904-c71cbe7a9a5d.png)
The same server configuration of others is 100% online, and I only 20%, this is why?? I am using debian system and using docker installation, is it because others use Ansible installation or something? I also want to go straight to 100%. Please help me with the answer, thank you.

**Comment by zxc348369518** [comment]
![image](https://user-images.githubusercontent.com/85321635/218228057-504da940-b412-4fc5-83b6-93617cfc47db.png)
th right

**Comment by zxc348369518** [comment]
![image](https://user-images.githubusercontent.com/85321635/218228085-99f6e49c-9c61-4536-8834-8e330dbe1842.png)
it show right

**Comment by DiegoRBaquero** [comment]
Can you please use the template and provide the exact node's IP?
