### ISSUE TITLE
compress compressable filetypes, dont compress everything else

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/L1-node#22]
* compress these filetypes: https://support.cloudflare.com/hc/en-us/articles/200168396-What-will-Cloudflare-compress-

* dont compress everything else to avoid needless compression on assets already compressed, like jpgs, mp4s, mp3s, etc

* compress either with gzip or brotli (#21), as supported by the client

**Comment by DiegoRBaquero** [comment]
Per top results in google, it makes sense to compress everything rather than not. Bandwidth is more expensive than CPU and we can later optimize by peeking into and compressing only the ones with actual gains.

**Comment by gruns** [comment]
> Per top results in google, it makes sense to compress everything rather than not.

link?

**Comment by DiegoRBaquero** [comment]
https://serverfault.com/questions/253074/what-is-the-best-nginx-compression-gzip-level
https://sudonull.com/post/172479-GZip-and-nginx-performance-impact
http://paulbuchheit.blogspot.com/2009/04/make-your-site-faster-and-cheaper-to.html
