### ISSUE TITLE
L1s return 500s most of the time

### ISSUE THREAD

**Issue by lidel** [filecoin-saturn/L1-node#222]
![hmpf](https://user-images.githubusercontent.com/157609/219253245-beb50259-95bf-416a-9059-49a6d88422bc.png)
![hm](https://user-images.githubusercontent.com/157609/219253062-4e3cc95a-abfd-46e1-a758-27faeec9f71b.png)

https://protocollabs.grafana.net/d/d6FxxgJ4k/bifrost-gw-metrics?orgId=1&from=now-24h&to=now&refresh=1m

**Comment by lidel** [comment]
Mystery solved:

> We proxy lassie status codes. 500 seems to be a really common error, so don't treat it like the L1 is erroring or w/e.
```
Error (500): Failed to fetch cid: query failed: failed to dial 12D3KooWDAHxZiMuQwX4Hwn4Rctje9RWWJB6FxhAa6aTuitTqmVx:
Error (500): Failed to fetch cid: no candidates
```

I think if it timeouts / cant find the content it should be adjusted to 504.

**Comment by guanzo** [comment]
Should be fixed by https://github.com/filecoin-project/lassie/commit/0f647ea3b1be160023bdef3d108783280e0f6e93
