### ISSUE TITLE
Remove SATURN_NETWORK environment variable

### ISSUE THREAD

**Issue by DiegoRBaquero** [filecoin-saturn/L1-node#225]
From docker compose and .env template

It should only come from the arg in the build.

Could it stop being a docker env variable and pass it from the arg to a file maybe?

**Comment by gruns** [comment]
> From docker compose and .env template

and the docs 🙂 (it's pervasive throughout the l1 readme and docs)

**Comment by joaosa** [comment]
Leaving this in the docs, as it's the way to specify if operators are fetching a test net or main net version. The issue is preventing this from getting passed into the container which https://github.com/filecoin-saturn/L1-node/pull/248 takes care of.

**Comment by joaosa** [comment]
This is no longer present as it can be seen [here](https://raw.githubusercontent.com/filecoin-saturn/L1-node/main/docker-compose.yml). Also deployed this change to all core nodes
