### ISSUE TITLE
increase the minimum ssd storage size from 2TB to 8TB in the docs, strn.network website, and everywhere else relevant

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/L1-node#230]

**Comment by chenmo1979** [comment]
What's the point? We can't even use up 1T now

**Comment by juliangruber** [comment]
The website currently lists 1TB https://strn.network/

**Comment by gruns** [comment]
@chenmo1979 a lot more usage is forthcoming; this is to help nodes maintain high cache hit rates
