### ISSUE TITLE
on ring nodes, and ring nodes only, return http 501 for all endpoints not supported by the trusteless gateway API

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/L1-node#232]
ring nodes should only support the https://github.com/ipfs/specs/blob/main/http-gateways/TRUSTLESS_GATEWAY.md spec and return 501 not implemented for all other gateway API endpoints. notably, ring nodes will no longer serve flat files responses

core nodes continue to implement the trustless gateway spec and all the other gateway specs and, in turn, thus continue to serve flat files

this is high priority

**Comment by guanzo** [comment]
Order of operations

- [ ] [Strn.pl points to core nodes only
](https://github.com/filecoin-saturn/orchestrator/issues/90)
- [ ] [merge PR](https://github.com/filecoin-saturn/L1-node/compare/disable-flat-file)
- [ ] run L1 ansible playbook to add the new `IS_CORE_L1` env var
- [ ] deploy to testnet
- [ ] deploy to prod
