### ISSUE TITLE
Geolocation fix

### ISSUE THREAD

**Issue by perfectyc** [filecoin-saturn/L1-node#234]
IP:103.150.120.35
Coordinates:
City:Surabaya
Region:East Java
Country:ID
Country Code:ID

IP:41.216.178.48
Coordinates:
City:Ubud
Region:Bali
Country:ID
Country Code:ID

This is the result of my query ipinfo.io, if saturn uses ipinfo, please synchronize the location information

**Comment by DiegoRBaquero** [comment]
Flushed our cache for these IPs
