### ISSUE TITLE
Geolocation fix: Doddaballapura -> Bangalore, India (IN)

### ISSUE THREAD

**Issue by up_the_irons** [filecoin-saturn/L1-node#243]
IP: 139.84.138.124
Coordinates: 12.979839878466143, 77.7256402574406
City: Bangalore
Region: Karnataka
Country: India
Country Code: IN

According to Vultr, this server is in Bangalore, about 40km away from Doddaballapura (which is what the GeoIP returns); so using Bangalore instead might be a little more accurate.

**Comment by DiegoRBaquero** [comment]
Missing the coordinates

**Comment by DiegoRBaquero** [comment]
If you can get the DC address that'd give the coordinates

**Comment by up_the_irons** [comment]
Hi Diego,

The DC address is:

Nxtra Data Limited
Plot no 111 & 112
EPIP Area, Opp to SJR Complex
Bangalore 560066, Karnataka
India

The coordinates are: 12.979839878466143, 77.7256402574406

**Comment by up_the_irons** [comment]
Edited my original comment and inserted the coordinates ✅

**Comment by up_the_irons** [comment]
👀

**Comment by DiegoRBaquero** [comment]
Overriden and cache flushed

**Comment by up_the_irons** [comment]
Thank you!
