### ISSUE TITLE
A lot of 404 and 504 errors with lassie

### ISSUE THREAD

**Issue by DVerdeV** [filecoin-saturn/L1-node#246]
For a few hours now, I've been seeing a lot of these errors, causing my cache percentage to drop quite a bit (from 100% to 54%).

![image](https://user-images.githubusercontent.com/99612385/221718197-3c2f97f4-cfb2-437c-a561-5777f7a2fbac.png)
![image](https://user-images.githubusercontent.com/99612385/221718215-16a7663f-4f7c-4778-b10e-d509fee275f1.png)
![image](https://user-images.githubusercontent.com/99612385/221718414-ec531928-9ebc-405b-b58c-a08704b839b3.png)

**Comment by DVerdeV** [comment]
Started to see some of these too…

![image](https://user-images.githubusercontent.com/99612385/221719136-aad9a55a-22ea-4a38-8d5b-5135f7793905.png)

**Comment by guanzo** [comment]
Ya this is unfortunately expected behavior until the lassie fetcher improves, it's a work in progress atm. 

Cache percentage should only count for successful retrievals. I believe that was addressed today with https://github.com/filecoin-saturn/L1-node/pull/254

**Comment by gruns** [comment]
- thank you for this issue, @DVerdeV! 🙏 
- closing this; as lassie's performance is now much improved and will continue to improve 🙌
