### ISSUE TITLE
FOR RHEA: Collect L1 metrics on how many requests they get from Bifrost

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-saturn/L1-node#261]
Bifrost/Caboose are looking into implementing better load distribution of requests across L1s. To measure that, we first need metrics from L1s on how many requests they're getting from Bifrost per minute/hour/day.  Can we implement this metrics collection in L1s and get the graph added to the Saturn dashboard ?

**Comment by DiegoRBaquero** [comment]
Is your idea to “if you have low reqs I’ll send you more” or the inverse? “You have a lot of reqs, I’ll stop sending”?DiegoOn 6/03/2023, at 1:43 AM, Aarsh Shah ***@***.***> wrote:﻿
Bifrost/Caboose are looking into implementing better load distribution of requests across L1s. To measure that, we first need metrics from L1s on how many requests they're getting from Bifrost per minute/hour/day.  Can we implement this metrics collection in L1s and get the graph added to the Saturn dashboard ?

**Comment by aarshkshah1992** [comment]
@DiegoRBaquero 

The idea is to have a way to measure how much we're improving the load balancing on the Caboose side of things by having the Saturn dashboard  show the distribution of Bifrost requests across L1s/have L1s report if they're getting too many requests from Bifrosyt. 

If we see this graph even out gradually, we know we're doing a good job with it. On the Caboose side, we're gonna use metrics such as observed latency etc to create a natural partition of L1s across the Bifrost instances spread across the globe.

**Comment by aarshkshah1992** [comment]
@DiegoRBaquero The problem is that we have multiple Bifrost instances spread across the globe. If the reputation as determined by the orchestrator  is all we care about when selecting which L1 to route requests to, there is a chance that the same set of good L1s get hammered with requests from all the Bifrost instances. 

So, we are going to change the Caboose algo to consider observed latencies as well when deciding which L1s to route the requests to so that there is some sort of natural partition of L1s across Bifrost nodes.

The only ask from Saturn here for now is that Saturn creates a dashboard showing the distribution of Bifrost requests across L1 instances.
