### ISSUE TITLE
investigate filled host logs to arrive at a solution

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/L1-node#31]
1. `/var/log/journal/*` is systemd logs. what, exactly, is in those logs? normal humdrum stuff or errors of some kind we should fix?

depending on the answer above

2. how should we help the node operator not fill their logs from running an l1? while host logs are the operator's responsibility, if saturn fills them up, helping them manage the host logs is our duty and responsibility

**Comment by DiegoRBaquero** [comment]
Where was this observed? @gruns @guanzo ? Largest nodes don't have more than a few gigs in `/var`, BOG for example:

```
0	/bin
301M	/boot
0	/dev
5.0M	/etc
28K	/home
0	/lib
0	/lib32
0	/lib64
0	/libx32
16K	/lost+found
8.0K	/media
4.0K	/mnt
16K	/opt
0	/proc
77G	/root
1.9M	/run
0	/sbin
8.0K	/snap
4.0K	/srv
0	/sys
56K	/tmp
3.0G	/usr
3.0G	/var
```

**Comment by guanzo** [comment]
I saw it on one of the nodes that was reporting 100% disk usage. None of the nodes are reporting that now so it's hard to find an example.

**Comment by gruns** [comment]
i created this issue so the original problem, commented here 

  * https://filecoinproject.slack.com/archives/C031K3BG527/p1658182248286159?thread_ts=1658181695.782469&cid=C031K3BG527

wouldnt get lost

@DiegoRBaquero does our existing fleet of servers already have log rotation in place? eg with `logrotate`?

**Comment by DiegoRBaquero** [comment]
They don't, but haven't seen logs occupy disk like that since

**Comment by gruns** [comment]
cool. so i say we

1. close this issue to keep focus
2. re-open it if/when another server's disk fills up with logs
3. keep in the back of our mind that we will/should help l1 operators deal with host system logs in the future

sgty, @DiegoRBaquero? if so, feel free to close this issue
