### ISSUE TITLE
Retrievals submit problem

### ISSUE THREAD

**Issue by lushdog** [filecoin-saturn/L1-node#314]
Hi, There is may be a problem bought from new version.  Retrievals submit may be missed due newly added log rotation. My node serves hundreds file each minute during some high traffic time. But log show "No retrievals" in many line. Is it normal? Looks like if   traffic go down, the problem is gone. 
![Snipaste_2023-03-31_17-52-51](https://static.mcc.miui.com/newhome/appUser/1680256682475/Snipaste_2023-03-31_17-52-51.png)

**Comment by lushdog** [comment]
Looks like it appears at beagin of hours. I am sure my node have hundreds retrievals.
![Snipaste_2023-03-31_18-13-01](https://static.mcc.miui.com/newhome/appUser/1680257604582/Snipaste_2023-03-31_18-13-01.png)
![Snipaste_2023-03-31_18-12-42](https://static.mcc.miui.com/newhome/appUser/1680257592119/Snipaste_2023-03-31_18-12-42.png)

**Comment by lushdog** [comment]
UPD: 11:00 has no problem.
Saturn-node  | 2023-03-31T10:59:27.429Z node@mainnet:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 208ms
saturn-node  | 2023-03-31T11:00:27.234Z node@mainnet:log-ingestor Submitting 9 retrievals (13.8 MB with cache rate of 100.0%)
saturn-node  | 2023-03-31T11:00:27.447Z node@mainnet:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 212ms
saturn-node  | 2023-03-31T11:01:27.249Z node@mainnet:log-ingestor Submitting 1 retrievals (1.26 kB with cache rate of 100.0%)
saturn-node  | 2023-03-31T11:01:27.453Z node@mainnet:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 204ms
saturn-node  | 2023-03-31T11:02:27.272Z node@mainnet:log-ingestor Submitting 5 retrievals (1.15 MB with cache rate of 100.0%)
saturn-node  | 2023-03-31T11:02:27.480Z node@mainnet:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 208ms
saturn-node  | 2023-03-31T11:03:27.291Z node@mainnet:log-ingestor Submitting 6 retrievals (499 kB with cache rate of 100.0%)
saturn-node  | 2023-03-31T11:03:27.498Z node@mainnet:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 207ms
saturn-node  | 2023-03-31T11:04:27.301Z node@mainnet:log-ingestor Submitting 5 retrievals (2.4 MB with cache rate of 100.0%)
saturn-node  | 2023-03-31T11:04:27.507Z node@mainnet:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 206ms
saturn-node  | 2023-03-31T11:05:27.309Z node@mainnet:log-ingestor Submitting 6 retrievals (7.57 MB with cache rate of 83.3%)
saturn-node  | 2023-03-31T11:05:27.514Z node@mainnet:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 205ms
saturn-node  | 2023-03-31T11:06:27.337Z node@mainnet:log-ingestor Submitting 8 retrievals (568 kB with cache rate of 100.0%)
saturn-node  | 2023-03-31T11:06:27.556Z node@mainnet:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 219ms
saturn-node  | 2023-03-31T11:07:27.370Z node@mainnet:log-ingestor Submitting 314 retrievals (65.4 MB with cache rate of 100.0%)

**Comment by DiegoRBaquero** [comment]
Each rotated file will have a log that has no new retrievals, but as you can see, retrievals are happening and being submitted.Will clean this up to only show one consolidated logDiegoOn 31/03/2023, at 6:13 AM, HoraceZhang ***@***.***> wrote:﻿
UPD: 11:00 has no problem.
Saturn-node  | 2023-03-31T10:59:27.429Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 208ms
saturn-node  | 2023-03-31T11:00:27.234Z ***@***.***:log-ingestor Submitting 9 retrievals (13.8 MB with cache rate of 100.0%)
saturn-node  | 2023-03-31T11:00:27.447Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 212ms
saturn-node  | 2023-03-31T11:01:27.249Z ***@***.***:log-ingestor Submitting 1 retrievals (1.26 kB with cache rate of 100.0%)
saturn-node  | 2023-03-31T11:01:27.453Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 204ms
saturn-node  | 2023-03-31T11:02:27.272Z ***@***.***:log-ingestor Submitting 5 retrievals (1.15 MB with cache rate of 100.0%)
saturn-node  | 2023-03-31T11:02:27.480Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 208ms
saturn-node  | 2023-03-31T11:03:27.291Z ***@***.***:log-ingestor Submitting 6 retrievals (499 kB with cache rate of 100.0%)
saturn-node  | 2023-03-31T11:03:27.498Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 207ms
saturn-node  | 2023-03-31T11:04:27.301Z ***@***.***:log-ingestor Submitting 5 retrievals (2.4 MB with cache rate of 100.0%)
saturn-node  | 2023-03-31T11:04:27.507Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 206ms
saturn-node  | 2023-03-31T11:05:27.309Z ***@***.***:log-ingestor Submitting 6 retrievals (7.57 MB with cache rate of 83.3%)
saturn-node  | 2023-03-31T11:05:27.514Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 205ms
saturn-node  | 2023-03-31T11:06:27.337Z ***@***.***:log-ingestor Submitting 8 retrievals (568 kB with cache rate of 100.0%)
saturn-node  | 2023-03-31T11:06:27.556Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 219ms
saturn-node  | 2023-03-31T11:07:27.370Z ***@***.***:log-ingestor Submitting 314 retrievals (65.4 MB with cache rate of 100.0%)

**Comment by lushdog** [comment]
> Each rotated file will have a log that has no new retrievals, but as you can see, retrievals are happening and being submitted.Will clean this up to only show one consolidated logDiegoOn 31/03/2023, at 6:13 AM, HoraceZhang ***@***.***> wrote:﻿ UPD: 11:00 has no problem. Saturn-node | 2023-03-31T10:59:27.429Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 208ms saturn-node | 2023-03-31T11:00:27.234Z ***@***.***:log-ingestor Submitting 9 retrievals (13.8 MB with cache rate of 100.0%) saturn-node | 2023-03-31T11:00:27.447Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 212ms saturn-node | 2023-03-31T11:01:27.249Z ***@***.***:log-ingestor Submitting 1 retrievals (1.26 kB with cache rate of 100.0%) saturn-node | 2023-03-31T11:01:27.453Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 204ms saturn-node | 2023-03-31T11:02:27.272Z ***@***.***:log-ingestor Submitting 5 retrievals (1.15 MB with cache rate of 100.0%) saturn-node | 2023-03-31T11:02:27.480Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 208ms saturn-node | 2023-03-31T11:03:27.291Z ***@***.***:log-ingestor Submitting 6 retrievals (499 kB with cache rate of 100.0%) saturn-node | 2023-03-31T11:03:27.498Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 207ms saturn-node | 2023-03-31T11:04:27.301Z ***@***.***:log-ingestor Submitting 5 retrievals (2.4 MB with cache rate of 100.0%) saturn-node | 2023-03-31T11:04:27.507Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 206ms saturn-node | 2023-03-31T11:05:27.309Z ***@***.***:log-ingestor Submitting 6 retrievals (7.57 MB with cache rate of 83.3%) saturn-node | 2023-03-31T11:05:27.514Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 205ms saturn-node | 2023-03-31T11:06:27.337Z ***@***.***:log-ingestor Submitting 8 retrievals (568 kB with cache rate of 100.0%) saturn-node | 2023-03-31T11:06:27.556Z ***@***.***:log-ingestor Retrievals submitted succesfully to wallet f1xxxxxx in 219ms saturn-node | 2023-03-31T11:07:27.370Z ***@***.***:log-ingestor Submitting 314 retrievals (65.4 MB with cache rate of 100.0%) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Hi, Could you see the image posted? How to explain from 9:00 to 9:42 there was no retrievals submit log? Did they be submitted after 9:42? The traffic was high during that time. It could 1000+ retrievals every min.
