### ISSUE TITLE
Readline.js bug due log logrorate

### ISSUE THREAD

**Issue by lushdog** [filecoin-saturn/L1-node#317]
Hi, this commit add logrorate https://github.com/filecoin-saturn/L1-node/commit/a2d19081490ac03b3e27ebd0a71c19a7ad561ec3. But I find my some nodes would not submit retrievals entire hour. I have opened a issue but you ingored it. So I read the code of readline.js [https://github.com/filecoin-saturn/L1-node/blob/main/container/shim/src/utils/readlines.js](url).
It use hashmap of log file's inode. However if a new node-access.log file happens to have the same inode as an old log file. Readline.js will always read zero line becase .offsetfile's offset number is the size of an old log file. 
So it will submit no retrieval util the new node-access.log' size goes bigger than that old log file

**Comment by lushdog** [comment]
There are logrorate log and node-access.log from 8:00 to 9:00
<img width="1311" alt="Snipaste_2023-04-02_17-27-43" src="https://user-images.githubusercontent.com/27630616/229344429-e3da1f53-8abc-4ecf-a7c9-fe6ca3a2a604.png">
<img width="1345" alt="Snipaste_2023-04-02_17-28-11" src="https://user-images.githubusercontent.com/27630616/229344435-2f19a44b-2679-45ad-9214-1f7d43054095.png">
[node-access.log](https://github.com/filecoin-saturn/L1-node/files/11131720/node-access.log)

**Comment by guanzo** [comment]
I'll take a look at this, thanks for reporting.

**Comment by lushdog** [comment]
> Looking into this as well. Why would the inode be repeated? When files are rotated, they are moved, so inode remains intact after going from `node-access.log` -> `node-access.log.1`. New `node-access.log` will have a new inode
Hi, Thanks for looking into this. This problem really annoyed me this days. I also finded many other charts showed discontinuous line.
eg: 19fc94aa-f413-47e6-bee2-d3715d7ba58b
eg: 798b3635-2674-4388-bb67-a3131399c38b
From my observation. It happened many times not just one case. Both bare metal servers using lvm partition or virtul machines. Of course the more inode stored in .offsetfile, the more chance to get repeated inode.
