### ISSUE TITLE
`update.sh` should revert if the container fails to start

### ISSUE THREAD

**Issue by guanzo** [filecoin-saturn/L1-node#32]
If the newly downloaded image fails to start, the updater script should find the latest working version and run that instead. Simply running the previous version won't suffice, as multiple images in a row may be broken. It should keep iterating previous versions until `docker run` succeeds.

**Comment by YurkoWasHere** [comment]
Recent comment makes update.sh obsolete in favor of watchtower. 

Can issue be closed?

**Comment by joaosa** [comment]
@YurkoWasHere sadly watchtower doesn't support [any form of rollback as of yet](https://github.com/containrrr/watchtower/issues/444).
