### ISSUE TITLE
Implement depth=0 for CAR requests

### ISSUE THREAD

**Issue by guanzo** [filecoin-saturn/L1-node#323]
Only return intermediate blocks + root block of last node of path.

**Comment by guanzo** [comment]
close in favor of https://github.com/ipfs/bifrost-gateway/issues/80

**Comment by lidel** [comment]
@hannahhoward  @guanzo  will `car-scope` and `bytes` be passed from L1 to Lassie as-is, or do we need to add them to https://github.com/filecoin-saturn/L1-node/blob/main/container/shim/src/fetchers/lassie.js?

**Comment by guanzo** [comment]
all query params get forwarded to lassie 
https://github.com/filecoin-saturn/L1-node/blob/4695c04d06f22850a4d8b45e2c2243c4c9e8baec/container/shim/src/fetchers/lassie.js#L155
