### ISSUE TITLE
Don't cache server-timing's

### ISSUE THREAD

**Issue by willscott** [filecoin-saturn/L1-node#348]
on cache responses, the `server-timing` headers from the initial fetch shouldn't be returned again - those timings aren't accurate for the cached response

**Comment by DiegoRBaquero** [comment]
I looked into this, but the headers are part of the cache and returned as-is. There's not way to condition the caching of headers :(

**Comment by willscott** [comment]
we have some logic for the 'is cache hit' header - can that also strip off
server timing headers on the response at that point?

**Comment by willscott** [comment]
cool. i think i'll close for now as 'not worth it'
