### ISSUE TITLE
https://dashboard.saturn.tech/stats healthcheck report UI bugs

### ISSUE THREAD

**Issue by KlausGlueckert** [filecoin-saturn/L1-node#353]
when clicking on a node the UI popup still has bugs:

* Invalid Date

`
Health Check Failures
Invalid Date Invalid Daterequest to https://152.xxx.xxx.130/ipfs/QmYsTqbmGA3H5cgouCkh8tswJAQE1AsEko9uBZX9jZ3oTC/twinkle.json?clientId=d6bf5382-5404-49db-a5a7-dfce813ba500&car-scope=file&format=car failed, reason: connect ECONNREFUSED 152.xxx.xxx.130:443
Invalid Date Invalid Date152.xxx.xxx.130 connection timed out after 4 retries
Invalid Date Invalid Date152.xxx.xxx.130 connection timed out after 4 retries
`

**Comment by DiegoRBaquero** [comment]
This was a two sided bug, orchestrator not sending the date and dashboard not reading the correct property. Both have been fixed.
