### ISSUE TITLE
Don't re-validate car streams from lassie

### ISSUE THREAD

**Issue by willscott** [filecoin-saturn/L1-node#361]
The l1 shim currently in a lassie car request follows
* [streamCar](https://github.com/filecoin-saturn/L1-node/blob/cde8e11477b4416bcc24a919ea8fb2fc622a0683/container/shim/src/fetchers/lassie.js#L123)
* [validateCarBlock](https://github.com/filecoin-saturn/L1-node/blob/cde8e11477b4416bcc24a919ea8fb2fc622a0683/container/shim/src/utils/car.js#L48)
* [digest](https://github.com/filecoin-saturn/L1-node/blob/cde8e11477b4416bcc24a919ea8fb2fc622a0683/container/shim/src/utils/car.js#L95)

This is a lot of CPU work to re-hash every block, which lassie has just validated on the same node. we should trust lassie as much as we trust L1 (they're the same trust domain) so re-hashing shouldn't be needed in this L1 shim path.

**Comment by DiegoRBaquero** [comment]
Fixed by https://github.com/filecoin-saturn/L1-node/commit/4c2676b31c8b856e308e0e77babb0af899ab88a5
