### ISSUE TITLE
RAW format handling doesn't work for path requests, should fail anyway for trustless

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-saturn/L1-node#401]
# What

Reading the code for [getRequestedBlockFromCar](https://github.com/filecoin-saturn/L1-node/blob/main/container/shim/src/fetchers/lassie.js#L259) it looks in cases where a path is passed for a RAW request, the returned block is root block, rather than block at the end of the path (which is what is supposed to happen for a RAW request in the Path gateway spec). However, this would be a trustful request anyway, because you don't have the blocks to verify the raw block at the end. so I think the proper behavior is to 400 any request in format=RAW where a path is present.

**Comment by guanzo** [comment]
>  I think the proper behavior is to 400 any request in format=RAW where a path is present.

sgtm, will fix soon

**Comment by guanzo** [comment]
Closed by https://github.com/filecoin-saturn/L1-node/pull/411
