### ISSUE TITLE
Geolocation fix

### ISSUE THREAD

**Issue by lnzx** [filecoin-saturn/L1-node#402]
IP: 45.89.55.187
Coordinates: 44.8040,20.4651
City: Belgrade
Region: Central Serbia
Country: Serbia
Country Code: RS

![image](https://github.com/filecoin-saturn/L1-node/assets/1515417/d3d7bdce-07dd-4bd1-a799-29f48b3297ad)

**Comment by DiegoRBaquero** [comment]
This is ipinfo, the provider we use, are you seeing something different in your logs?

**Comment by lnzx** [comment]
The log shows that the location of this IP is in the United States:
`Node's geolocation is set to Seattle, Washington, United States. If this is wrong, please open an issue at https://github.com/filecoin-saturn/L1-node/issues`
