### ISSUE TITLE
Geolocation fix

### ISSUE THREAD

**Issue by nkulskswaemkiula** [filecoin-saturn/L1-node#423]
IP:64.44.86.209
Coordinates:37.3382,-121.886
City:San Jose
Region:California
Country:USA
Country Code:US
![209](https://github.com/filecoin-saturn/L1-node/assets/135698442/f0873798-b840-4f74-980e-cf632fedede1)

**Comment by DiegoRBaquero** [comment]
Based on ping testing, this host is located in Denver, not San Jose
