### ISSUE TITLE
Geolocation fix

### ISSUE THREAD

**Issue by nkulskswaemkiula** [filecoin-saturn/L1-node#424]
IP:64.44.86.215
Coordinates:42.8867,-78.8927
City:New York
Region:New York
Country:USA
Country Code:US
![215](https://github.com/filecoin-saturn/L1-node/assets/135698442/91511deb-9f6b-4ee6-8744-9eca1a07a12d)

**Comment by DiegoRBaquero** [comment]
Same with this IP, based on ping testing, it's located in Denver
