### ISSUE TITLE
Run conformance test in CI

### ISSUE THREAD

**Issue by willscott** [filecoin-saturn/L1-node#447]
the gateway conformance test suite should be run / pass in CI against the L1 node

**Comment by willscott** [comment]
it looks like we have running but not passing: https://github.com/filecoin-saturn/L1-node/actions/workflows/gateway-conformance.yml

**Comment by guanzo** [comment]
Depends on: 
https://github.com/ipfs/gateway-conformance/issues/83
https://github.com/ipfs/gateway-conformance/issues/74

**Comment by laurentsenta** [comment]
Team, we merged the PRs above and released v0.2, you should have everything to setup the test suite!
Don't hesitate to open an issue in the [repo](https://github.com/ipfs/gateway-conformance) or reach out on Slack (`#ipfs-gateway-conformance`) if we can help,

A few examples from other repos:
- [Kubo](https://github.com/ipfs/kubo/blob/master/.github/workflows/gateway-conformance.yml), full setup, with ipns, dnslink, etc.
- [Boxo](https://github.com/ipfs/boxo/blob/main/.github/workflows/gateway-conformance.yml), minimal setup, no ipns or dnslink
