### ISSUE TITLE
Geolocation fix

### ISSUE THREAD

**Issue by neicedai** [filecoin-saturn/L1-node#466]
IP:147.124.201.0/24
Coordinates:40.7143,-74.0060
City:New York
Region:New York (NY)
CountryUnited States (US)
Country Code:10002

Please check these ips 
It should be NewYork City not Ashburn

**Comment by DiegoRBaquero** [comment]
There are multiple node ops in the range.

Please provide the specific range with proof of rent/ownership so we can fix those geolocations

**Comment by neicedai** [comment]
How to upload a picture?

**Comment by DiegoRBaquero** [comment]
Drag and drop

**Comment by neicedai** [comment]
![tier](https://github.com/filecoin-saturn/L1-node/assets/37585056/9ec4d1fe-caa7-4c0b-a711-ad94c7e1a301)
147.124.201.56

**Comment by DiegoRBaquero** [comment]
Should I only update 147.124.201.56 then?

**Comment by neicedai** [comment]
147.124.201.56 and 147.124.201.57
Thanks

**Comment by DiegoRBaquero** [comment]
Should be up in 10 mins
