### ISSUE TITLE
Split built into steps and cache them immediately in case build fails

### ISSUE THREAD

**Issue by DiegoRBaquero** [filecoin-saturn/L1-node#519]
If the build fails (30 mins in), nothing is cached.

Staging Build # 1: https://github.com/filecoin-saturn/L1-node/actions/runs/7544007092
Prod Build # 1: https://github.com/filecoin-saturn/L1-node/actions/runs/7544206550/attempts/1
Prod Build # 2: https://github.com/filecoin-saturn/L1-node/actions/runs/7544206550/attempts/2

Research caching intermediate steps built immediately: https://github.com/docker/build-push-action/issues/756

**Comment by wilkyr31d** [comment]
Build was not ssplit into steps - not 2worth doing that at thiss time. But underlying problem is now resolved so closing this
