### ISSUE TITLE
Switching node id causes nginx to still send old one

### ISSUE THREAD

**Issue by DiegoRBaquero** [filecoin-saturn/L1-node#522]
When a node operator switches IP and/or node ID, nginx still sends the old one instead of the new one. This is causing issues of "missed" earnings or sending new earnings to old ID and possibly old/previous wallet

**Comment by hannahhoward** [comment]
1/23 still working

**Comment by DiegoRBaquero** [comment]
- Checked bashed script and nginx config. Tried to replicate with switch and removal of old node id. Couldn't replicate
- Pushing a new prod version, forcing everyone to rehash their current ID with latest version
