### ISSUE TITLE
check and enforce hardware requirements on setup

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/L1-node#80]
on l1 node startup, check if the node satisfies the minimum hardware requirements. and, if not:

* inform the user that their node needs to meet the minimum hardware requirements to participate in saturn
* enumerate each minimum hardware requirement that wasnt met so they have immediate, actionable feedback on what hardware needs to be upgraded to meet the minimum hardware requirements

open question:
- where/how are the hardware requirements stored? are they baked into the l1? or retrieved, like in json form, from the orchestrator?

**Comment by DiegoRBaquero** [comment]
Orchestrator now has `/requirements` endpoint which L1s use before registering to verify and provide immediate feedback.
